source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'PagingMenuController'
pod 'SnapKit'
pod 'ReachabilitySwift'
pod 'Kingfisher'
pod 'Fabric'
pod 'Crashlytics'
pod 'SwiftDate'
