target 'V2EX' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'PagingMenuController'
pod 'SnapKit'
pod 'ReachabilitySwift'
pod 'Kingfisher'
pod 'Fabric'
pod 'Crashlytics'
pod 'SwiftDate'
pod 'Ji'
pod 'RealmSwift'
pod 'ReactiveCocoa'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'KVOController', '~> 1.0.3'
end